version: '3.9'
services:
  dev-db:
    image: postgres:14
    ports:
      - 5434:5432
    env_file:
      - .env
  test-db:
    image: postgres:14
    ports:
      - 5435:5432
    env_file:
      - .env
